name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
       uses: actions/checkout@v3
       name: Build the Docker image
    
    -
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      
    -
      name: Build and push Dockerfile
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mongodb-backup-arvan-s3:${{ steps.date.outputs.date }}
#         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mongodb-backup-arvan-s3:${{ github.sha}}

